name: Build and Scan
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install node.js 18.x
        uses: actions/setup-node@v3
        with: 
          node-version: 18.x
      - name: Install Dependencies
        run: npm clean-install
        
      - name: Daemonize our Node API service
        run: npm start &
      - name: Run HawkScan
        uses: stackhawk/hawkscan-action@v1.3.4
        with:
          apiKey: ${{ secrets.HAWK_API_KEY }}
